name: Claude Code Test

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

jobs:
  claude-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Claude Code
        run: |
          npm install -g @anthropic-ai/claude-code
          echo "Claude Code installed successfully"
          
      - name: Verify Claude Code Installation
        run: |
          claude --version
          echo "Claude Code version check completed"
          
      - name: Test OAuth Token
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "Testing OAuth token authentication..."
          # Test basic Claude Code functionality
          claude --help
          echo "OAuth token test completed"
          
      - name: Test Basic Claude Functionality
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "Testing basic Claude functionality..."
          # Add a simple test command here
          echo "print('Hello from Claude!')" > test.py
          claude "Review this Python file" test.py || echo "Claude command failed, but workflow continues"